/* Índice das leituras — resumos de estudo em leituras/*.html.
   `area` liga a leitura ao tema do banco de questões (taxonomia.js) e alimenta o
   botão "treinar questões". `min` é o tempo estimado de leitura. */
window.LEITURAS=[
 {grupo:"Fundamentos da perícia", sub:"comece por aqui"},
 {f:"exame-aptidao-fisica-mental.html", tipo:"Guia da norma", area:"aptidao", min:12,
  t:"Exame de aptidão física e mental",
  s:"Resolução 927/2022 inteira: os 4 procedimentos do art. 4º, os 4 resultados, a periodicidade 10/5/3, as três juntas e o credenciamento."},
 {f:"exame-toxicologico.html", tipo:"Guia da norma", area:"legislacao", min:9,
  t:"Exame toxicológico de larga janela",
  s:"Art. 148-A e as quatro infrações do CTB: janela de 90 dias, o ciclo de 2 anos e 6 meses, a suspensão de 3 meses e a extensão às categorias A e B."},

 {grupo:"Exames específicos", sub:"os anexos com números de corte"},
 {f:"avaliacao-oftalmo-orl.html", tipo:"Tabelas de corte", area:"oftalmo", min:11,
  t:"Avaliação oftalmológica e otorrinolaringológica",
  s:"Anexos II, III e IV: acuidade e campo por categoria, olho único, estrabismo, lentes intraoculares e o degrau dos 40 dB na orelha melhor."},
 {f:"avaliacao-cardiorrespiratoria.html", tipo:"Tabelas de corte", area:"cardio", min:15,
  t:"Avaliação cardiorrespiratória",
  s:"Anexos V, VI e VII e a diretriz de dispositivos implantáveis: as três faixas de pressão, infarto 8 × 12 semanas, marca-passo, CDI e síncope."},
 {f:"avaliacao-neurologica.html", tipo:"Tabelas de corte", area:"neuro", min:16,
  t:"Avaliação neurológica e epilepsia",
  s:"Anexos VIII e IX contra a diretriz ABRAMET 2025: dinamometria 20/30 kgf, os dois grupos, a coluna da atividade remunerada, Parkinson e esclerose múltipla."},
 {f:"sono-fadiga-saos.html", tipo:"Tabelas de corte", area:"sono", min:11,
  t:"Sono, fadiga e apneia obstrutiva",
  s:"Anexos X, XI e XII: quem é rastreado, os quatro indícios objetivos mais o Epworth, a regra dos “dois ou mais” e a contradição do texto oficial."},
 {f:"locomotor-pessoa-com-deficiencia.html", tipo:"Guia da norma", area:"locomotor", min:14,
  t:"Aparelho locomotor e pessoa com deficiência",
  s:"Junta Médica Especial e NBR 14970, o resultado “apto com restrições”, os 22 códigos do Anexo XV e os prazos do recurso ao CETRAN."},

 {grupo:"Fatores de risco", sub:"o que tira a atenção e a capacidade"},
 {f:"alcool-direcao-veicular.html", tipo:"Guia clínico-legal", area:"alcool", min:10,
  t:"Álcool e direção veicular",
  s:"Os dois limiares — tolerância zero do art. 276 e o patamar penal do art. 306 —, a recusa, a farmacocinética do etanol e os erros do etilômetro."},
 {f:"falha-atencao-celular.html", tipo:"Guia de evidência", area:"epidemiologia", min:10,
  t:"Falha de atenção ao conduzir e o telefone celular",
  s:"Diretriz ABRAMET 2021: por que o viva-voz não resolve, o risco de 23×, os 30,2% da PRF e os incisos V e VI do art. 252."},

 {grupo:"Os outros eixos do edital", sub:"curativa, aeroespacial, viajante e securitária"},
 {f:"aph-trauma.html", tipo:"Protocolos", area:"curativa", min:16,
  t:"Atendimento pré-hospitalar e trauma",
  s:"Protocolos do SAMU 192 e o dever legal de socorrer: avaliação primária BT1, torniquete, regra dos 9 e o método START — com CINZA, não preto."},
 {f:"medicina-aeroespacial.html", tipo:"Guia da norma", area:"aeroespacial", min:15,
  t:"Medicina aeroespacial",
  s:"RBAC 67 da ANAC: as cinco classes de CMA e suas validades, requisitos clínicos, as três leis dos gases, hipóxia e tempo útil de consciência."},
 {f:"medicina-do-viajante.html", tipo:"Guia de evidência", area:"viajante", min:12,
  t:"Medicina do viajante",
  s:"Os prazos que organizam o eixo: 10 dias da febre amarela e o CIVP vitalício, as 4 horas da trombose do viajante, 12/24 horas entre mergulhar e voar."},
 {f:"dano-corporal-securitaria.html", tipo:"Tabelas de corte", area:"securitaria", min:13,
  t:"Dano corporal e medicina securitária",
  s:"O barema da Lei 6.194/1974 bloco a bloco, a graduação 75/50/25/10%, o pagamento sem discussão de culpa e a confusão DPVAT × SPVAT."}
];
