/* Índice das leituras — resumos de estudo em leituras/*.html.
   `area` liga a leitura ao tema do banco de questões (taxonomia.js) e alimenta o
   botão "treinar questões". `min` é o tempo estimado de leitura. */
window.LEITURAS=[
 {grupo:"Revisão final", sub:"a semana da prova"},
 {f:"revisao-vespera-numeros.html", tipo:"Tabelas de corte", area:"aptidao", min:30,
  t:"Revisão de véspera: os números que caem",
  s:"Todos os cortes da prova com a fonte ao lado: 10/5/3 anos, 20/30/40 pontos, 20/25 e 120º, 40 dB, IAM 8 × 12, 20 × 30 kgf, CMA por classe, DPVAT 13.500/2.700 — e o plano de quinta a sábado."},

 {grupo:"Fundamentos da perícia", sub:"comece por aqui"},
 {f:"exame-aptidao-fisica-mental.html", tipo:"Guia da norma", area:"aptidao", min:12,
  t:"Exame de aptidão física e mental",
  s:"Resolução 927/2022 inteira: os 4 procedimentos do art. 4º, os 4 resultados, a periodicidade 10/5/3, as três juntas e o credenciamento."},
 {f:"exame-toxicologico.html", tipo:"Guia da norma", area:"legislacao", min:9,
  t:"Exame toxicológico de larga janela",
  s:"Art. 148-A e as quatro infrações do CTB: janela de 90 dias, o ciclo de 2 anos e 6 meses, a suspensão de 3 meses e a extensão às categorias A e B."},
 {f:"ctb-essencial-perito.html", tipo:"Guia da norma", area:"legislacao", min:16,
  t:"CTB essencial para o perito de trânsito",
  s:"Categorias A–E e ACC, os 21 anos e o tempo de habilitação para D e E, a periodicidade 10/5/3, pontos 20/30/40, as infrações de saúde e as penas dos crimes do art. 302 ao 312-B."},

 {grupo:"Exames específicos", sub:"os anexos com números de corte"},
 {f:"avaliacao-oftalmo-orl.html", tipo:"Tabelas de corte", area:"oftalmo", min:11,
  t:"Avaliação oftalmológica e otorrinolaringológica",
  s:"Anexos II, III e IV: acuidade e campo por categoria, olho único, estrabismo, lentes intraoculares e o degrau dos 40 dB na orelha melhor."},
 {f:"avaliacao-otorrino.html", tipo:"Tabelas de corte", area:"orl", min:14,
  t:"Avaliação otorrinolaringológica",
  s:"Anexos III e IV: voz coloquial a 2 m, média de 500/1000/2000 Hz na orelha melhor, o degrau dos 40 dB, prótese (código B), surdez total só ACC/A/B e o otoneurológico obrigatório."},
 {f:"avaliacao-cardiorrespiratoria.html", tipo:"Tabelas de corte", area:"cardio", min:15,
  t:"Avaliação cardiorrespiratória",
  s:"Anexos V, VI e VII e a diretriz de dispositivos implantáveis: as três faixas de pressão, infarto 8 × 12 semanas, marca-passo, CDI e síncope."},
 {f:"avaliacao-neurologica.html", tipo:"Tabelas de corte", area:"neuro", min:16,
  t:"Avaliação neurológica e epilepsia",
  s:"Anexos VIII e IX contra a diretriz ABRAMET 2025: dinamometria 20/30 kgf, os dois grupos, a coluna da atividade remunerada, Parkinson e esclerose múltipla."},
 {f:"sono-fadiga-saos.html", tipo:"Tabelas de corte", area:"sono", min:11,
  t:"Sono, fadiga e apneia obstrutiva",
  s:"Anexos X, XI e XII: quem é rastreado, os quatro indícios objetivos mais o Epworth, a regra dos “dois ou mais” e a contradição do texto oficial."},
 {f:"locomotor-pessoa-com-deficiencia.html", tipo:"Guia da norma", area:"locomotor", min:14,
  t:"Aparelho locomotor e pessoa com deficiência",
  s:"Junta Médica Especial e NBR 14970, o resultado “apto com restrições”, os 22 códigos do Anexo XV e os prazos do recurso ao CETRAN."},
 {f:"diabetes-drc-sistemicas.html", tipo:"Guia clínico-legal", area:"sistemicas", min:15,
  t:"Diabetes, doença renal crônica e outras sistêmicas",
  s:"Diretrizes ABRAMET de diabetes e DRC dialítica: 12 meses sem hipoglicemia grave, glicemia ≥ 70 mg/dl antes de dirigir, 3 meses de diálise, ganho interdialítico ≤ 4,5% e prazo nunca acima de 5 anos."},

 {grupo:"Fatores de risco", sub:"o que tira a atenção e a capacidade"},
 {f:"alcool-direcao-veicular.html", tipo:"Guia clínico-legal", area:"alcool", min:13,
  t:"Álcool e direção veicular",
  s:"Os dois limiares — tolerância zero do art. 276 e o patamar penal do art. 306 —, a recusa, a farmacocinética do etanol e os erros do etilômetro."},
 {f:"medicamentos-drogas.html", tipo:"Guia clínico-legal", area:"drogas", min:16,
  t:"Medicamentos e drogas ilícitas na direção",
  s:"O que o CTB diz (e não diz) sobre substância lícita, o prejuízo equivalente a 0,3–0,5 g/L, as 2 semanas do benzodiazepínico, as categorias I/II/III do ICADTS e o toxicológico positivo por uso lícito."},
 {f:"psiquiatria-neurodesenvolvimento.html", tipo:"Guia clínico-legal", area:"psiq", min:14,
  t:"Avaliação psiquiátrica e neurodesenvolvimento",
  s:"Pergunta 4 do Anexo I e art. 147 §§3º–4º; esquizofrenia só na B (12 meses de aderência, 6 sem surto); fluxograma do TDAH (2/5 e 2/3 anos); TEA com avaliação psicológica em toda renovação."},
 {f:"falha-atencao-celular.html", tipo:"Guia de evidência", area:"epidemiologia", min:10,
  t:"Falha de atenção ao conduzir e o telefone celular",
  s:"Diretriz ABRAMET 2021: por que o viva-voz não resolve, o risco de 23×, os 30,2% da PRF e os incisos V e VI do art. 252."},
 
 {grupo:"Proteção e grupos especiais", sub:"quem está no veículo e quem está na via"},
 {f:"protecao-veicular-criancas.html", tipo:"Guia clínico-legal", area:"protecao", min:16,
  t:"Biomecânica, proteção veicular e transporte de crianças",
  s:"Energia proporcional a v², pedestre 10% a 30 km/h e 80% a 50 km/h, os quatro degraus da Resolução 819 (1 ano/13 kg, 4 anos, 7,5 anos, 1,45 m), a criança na ambulância e o pet no banco traseiro."},
 {f:"grupos-especiais.html", tipo:"Guia clínico-legal", area:"grupos", min:15,
  t:"Idoso, gestante, motociclista e ciclista",
  s:"Exame a cada 10/5/3 anos, MEEM, Mini-Cog e TUG no idoso; cinto de 3 pontos na gestante; art. 244 (capacete, viseira, criança menor de 10 anos na moto) e os 1,50 m do art. 201."},

 {grupo:"Os outros eixos do edital", sub:"curativa, aeroespacial, viajante, ocupacional, aquaviária e securitária"},
 {f:"aph-trauma.html", tipo:"Protocolos", area:"curativa", min:16,
  t:"Atendimento pré-hospitalar e trauma",
  s:"Protocolos do SAMU 192 e o dever legal de socorrer: avaliação primária BT1, torniquete, regra dos 9 e o método START — com CINZA, não preto."},
 {f:"medicina-aeroespacial.html", tipo:"Guia da norma", area:"aeroespacial", min:15,
  t:"Medicina aeroespacial",
  s:"RBAC 67 da ANAC: as cinco classes de CMA e suas validades, requisitos clínicos, as três leis dos gases, hipóxia e tempo útil de consciência."},
 {f:"medicina-do-viajante.html", tipo:"Guia de evidência", area:"viajante", min:12,
  t:"Medicina do viajante",
  s:"Os prazos que organizam o eixo: 10 dias da febre amarela e o CIVP vitalício, as 4 horas da trombose do viajante, 12/24 horas entre mergulhar e voar."},
 {f:"medicina-trafego-ocupacional.html", tipo:"Guia da norma", area:"ocupacional", min:15,
  t:"Medicina de tráfego ocupacional",
  s:"Lei 13.103 depois da ADI 5322: 5h30 ao volante, as pausas de 30 min, as 11 h de descanso sem fracionar, os prazos do toxicológico, PCMSO e ASO da NR-07 e a vibração de corpo inteiro."},
 {f:"medicina-aquaviaria.html", tipo:"Guia da norma", area:"aquaviaria", min:16,
  t:"Medicina de tráfego aquaviária",
  s:"NORMAM-211 (amadores, atestado, CHA e embriaguez a bordo), MLC 2006 e as diretrizes OIT/OMI do exame do marítimo, cinetose, hipotermia e atendimento a bordo."},
 {f:"dano-corporal-securitaria.html", tipo:"Tabelas de corte", area:"securitaria", min:13,
  t:"Dano corporal e medicina securitária",
  s:"O barema da Lei 6.194/1974 bloco a bloco, a graduação 75/50/25/10%, o pagamento sem discussão de culpa e a confusão DPVAT × SPVAT."}
];
